# AppVeyor (https://www.appveyor.com) continous integration configuration file for Windows unit tests
build: off

environment:
  PYTHONUNBUFFERED: 1
  matrix:
    - PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
      NOXSESSION: "tests-3.6"

    - PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"
      NOXSESSION: "tests-3.7"

install:
  # Prepend the right Python version to the PATH of this build
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Update Python stuff to make sure pip, setuptools, wheel etc are up to date
  - "python -m pip install -U --user pip setuptools setuptools_scm flake8 nox"

test_script:
- "python -m nox --non-interactive --session %NOXSESSION%"
