language: python
sudo: false  # enable container-based build
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  # - TOXENV=py35 https://github.com/travis-ci/travis-ci/issues/4794
  - TOXENV=pypy
install:
  - pip install tox
script:
  - tox
