name: CI

on:
  push:
    branches:
      - master
      - 2.0
  pull_request:
    branches:
      - master
      - 2.0

env:
  PYTHON_LATEST: 3.9

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9, 3.10-dev]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.pythonLocation }}/bin/*
            ${{ env.pythonLocation }}/lib/*
            ${{ env.pythonLocation }}/scripts/*
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('setup.py', 'requirements.txt') }}
      - name: Install python prerequisites
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          pip install -Ur pip install flake8 nox
          python setup.py develop
      - name: Lint
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == env.PYTHON_LATEST
        run: flake8 . --count --ignore=E252,W503 --max-complexity=26 --max-line-length=127 --show-source --statistics ;
      - name: Run tests and post coverage results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: nox --non-interactive
