# For documentation on GitHub Actions Workflows, see:
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Lint

on:
  push:
    branches:
      - master
      - 2.0
  pull_request:
    branches:
      - master
      - 2.0

env:
  PYTHON_LATEST: 3.9

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2  # https://github.com/actions/checkout
        with:
          # Only a single commit is fetched by default, for the ref/SHA that triggered the workflow.
          # Set fetch-depth: 0 to fetch all history for all branches and tags.
          fetch-depth: 0 # Needed for setuptools_scm to work correctly
      - name: Set up Python
        uses: actions/setup-python@v2  # https://github.com/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2  # https://github.com/actions/cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('setup.py') }}
      - name: Install python prerequisites
        # Only install dependencies when there is a cache miss
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: pip install -U --user pip setuptools setuptools-scm flake8 nox
      - name: Lint
        run: python -m flake8 . --count --ignore=E252,W503 --max-complexity=26 --max-line-length=127 --show-source --statistics ;
